### ISSUE TITLE
Support for .wav files

### ISSUE THREAD

**Issue by Karrzun** [yoadey/choreomusic#2]
Nice idea. We keep our music files in a .wav format, though, and it seems those are not yet supported.
The app per se makes a pretty neat first impression!

Edit: obviously, other formats might be interesting too, while are at it anyway. ;) I do use some wma files for example, but their amount is negligible

**Comment by yoadey** [comment]
Hello and thanks for the hint!
I've always worked with mp3 and never considered other file formats, but it's a good point and I'll try to add them!
I'm not sure though, whether the export/share functionality will work with those (basically whether the other file formats have Support for chapters, too), will try and test it!

**Comment by yoadey** [comment]
I know it is a long time gone, since the issue was reported, but it's finally available with .wav support as a test release. @Karrzun  if you join the  beta testing program, you should be able to get the latest version which also has support for .wav files. Could you test it and give feedback?

**Comment by yoadey** [comment]
Support for wav files was added and is now in the released version
